Fix bug with batches of size 1 with text model + install `libgl1-mesa-glx` package in Dockerfile
ShopRunner/octopod pull request #32
Opened 2020-10-29 16:53 UTC by nathancooperjones

Since I introduced this bug in a recent PR, I figured it would make sense for me to fix it. 

**Changes**: 
* Recently, we discovered that is a batch of size 1 is sent to the image model, it will error out due to an issue with `nn.BatchNorm1d` requiring a batch of size > 1. I fixed this by adding a check in `learner.py` that sees if the batch is of size 1 and, if so, skips it. It turns out that the text model has a different input structure than the vision + ensemble model that was not caught in that check, resulting in an error trying to train a text model. I fixed this by specifying the check to only work if the input `x` is a `dict` (vision + ensemble models have this input, but not the text model). This is worth triple-checking that all the tutorials work, but in my testing, things seem to work! 
* When running the `Dockerfile`, I found an error when trying to import `octopod` (`ImportError: libGL.so.1: cannot open shared object file: No such file or directory`) that I could only solve by running `apt install libgl1-mesa-glx`. I added this to the `Dockerfile`. 
* When running `octopod` on my computer, I ran into an issue where the learner would error out with an out-of-memory exception I could only fix by reducing the `num_workers` in the `DataLoaders`. I added a note to the two relevant tutorial notebooks with this caveat and instructions on how to fix it if it pops up. 
* [Optional] I think it makes more sense for the `Dockerfile` to install the `octopod` library along with the other `requirements.txt` so a user can run the `Dockerfile` commands and instantly jump into the tutorial notebooks. If we don't like this, I can always take it out. 

Pull Request Checklist
 - [X] All tests in the `tests` folder pass with a local build
 - [X] Pull request includes a description of why we are doing this
 - [ ] Init files import new capabilities to appropriate level of package (if applicable)
 - [X] CHANGELOG has been updated
 - [X] Version in `_version.py` has been updated
 - [ ] README has been updated (if applicable)

2020-10-29 17:33 UTC, jscottcronin requested changes
Let's sync up on zoom / or back and forth in this PR. I'm struggling to understand how it was working before and how this fix helps

2020-10-29 17:33 UTC, jscottcronin commented on Dockerfile
> +RUN pip install -e .
I'm surprised we can do this before we copy over all the octopod files 🦦

2020-10-29 17:33 UTC, jscottcronin commented on notebooks/fashion_data/Step2_train_image_model.ipynb
> +    "Try lowering the `num_workers` to `0` for each `DataLoader` in `train_dataloaders_dict` and `valid_dataloaders_dict`. "
nice!

2020-10-29 17:33 UTC, jscottcronin commented on octopod/learner.py
> +                if isinstance(x, dict) and x[next(iter(x))].shape[0] == 1:
I'm struggling to understand what is happening here. Can we clarify on what x is?

2020-10-29 19:39 UTC, nathancooperjones commented on octopod/learner.py
> +                if isinstance(x, dict) and x[next(iter(x))].shape[0] == 1:
I just re-factored this line to be a lot simpler - I think this might clarify exactly what we are trying to do with this.

2020-11-03 17:57 UTC, jscottcronin approved these changes
LGTM

2020-11-03 17:57 UTC, jscottcronin commented on octopod/learner.py
> +                    # skip batches of size 1
perfect!

2020-11-03 17:57 UTC, jscottcronin commented on octopod/learner.py
> +                    # skip batches of size 1
perfect! I'm not seeing where _get_num_rows was defined. Was that added in this PR?

2020-11-03 18:52 UTC, nathancooperjones commented on octopod/learner.py
> +                    # skip batches of size 1
I'm not sure when it was added, but it was there pre-this PR: https://github.com/ShopRunner/octopod/blob/wip/octopod/learner.py#L318

2020-11-03 18:52 UTC, merged