DS-2579: Accepting string labels
ShopRunner/octopod pull request #43
Opened 2021-02-03 17:40 UTC by sugi-chan

reason: allow octopod to take string labels as well as encoded labels. Basically the strategy is to use sklearn encoders to handle the incoming data in the dataset classes. The dataset classes then pass the label mappings to the dataloader class and when the learner is created it checks the train and val data loaders to make sure the label mappings are the same (a potential issue is that since the encoders are run on each dataset you might not have a certain class represented and so your train and val sets would have different label maps... which would be bad)

Pull Request Checklist
 - [ ] All tests in the `tests` folder pass with a local build
 - [ ] Pull request includes a description of why we are doing this
 - [ ] Init files import new capabilities to appropriate level of package (if applicable)
 - [ ] CHANGELOG has been updated
 - [ ] Version in `_version.py` has been updated
 - [ ] README has been updated (if applicable)
 - [ ] `requirements.txt` and `requirements-dev.txt` have been recompiled if requirements in `setup.py` or `requirements-dev.in` changed.

2021-02-04 18:54 UTC, nathancooperjones requested changes
This PR is awesome! I left some suggestions, some of which are overly nitpick-y and you can just ignore. Nice work so far! 

![](https://media.tenor.com/images/72cd8e758e7518d83eefdddb217743fb/tenor.gif)

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/dataloader.py
> +            mapping_dict[key] = self.loader_dict[key].dataset.label_mapping
[Optional] This is pretty picky on my end (sorry), but it might read a bit nicer if we refactor this to: 

```python
for key, loader_dict in self.loader_dict.items():
    mapping_dict[key] = loader_dict.dataset.label_mapping
```

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        le = preprocessing.LabelEncoder()
I didn't realize that, if given numeric inputs, `LabelEncoder` will make sure the mapping dictionary is numeric. Really neat! 

```python
>>> from sklearn import preprocessing
>>> le = preprocessing.LabelEncoder()
>>> y = [3, 2, 1, 0, 0, 8, 4, 5, 6, 7]
>>> le.fit(y)
LabelEncoder()
>>> dict(zip(le.transform(le.classes_), le.classes_))
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}
```

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        """Encodes y labels using sklearn to create allow for string or numeric inputs"""
```suggestion
        """Encodes string or numeric y labels to integers using LabelEncoder"""
```

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        """Encodes y labels using sklearn to create allow for string or numeric inputs"""
```suggestion
        """Encodes string or numeric y labels to integers using MultiLabelBinarizer"""
```

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        """Encodes y labels using sklearn to create allow for string or numeric inputs"""
You don't have to use this exact language, but I think it could be nice to make it clear exactly what is happening here.

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        label = self.label_encoder.transform([label])[0]
```suggestion
        label = self.label_mapping[label]
```

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        label = self.label_encoder.transform([label])[0]
If we make this change, is there a reason to save `self.label_encoder` at all? Can we only use the mapping and still get by?

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        using a sklearn label encoder
Can we also add an example here with a sample list of strings?

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        a list of binary encoded categories or strings with length equal to number of
Is the expected `y` here a list of lists?

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        which will be encoded using a sklearn label encoder
Wait... is this right? I thought this just needs a list, and `OctopodEnsembleDatasetMultiLabel` requires a list of lists?

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/learner.py
> +                raise Exception(f'Mapping mismatch in {task} task. Check that all categories are '
Nice descriptive error message!

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/learner.py
> +                raise Exception(f'Mapping mismatch in {task} task. Check that all categories are '
[Optional] It might be clearer to raise a `ValueError` here instead of a general `Exception` - what do you think?

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/learner.py
> +        self._check_all_labels_present()
Can we add a small note to the docstring above this to say that we expect the labels of `train_dataloader` to exactly match that of `val_dataloader`?

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/text/dataset.py
> +        will be encoded using an sklearn label encoder
Same question here about list of lists - I think I might just be confused hahaha so my bad

2021-02-04 18:54 UTC, nathancooperjones commented on octopod/text/dataset.py
> +    def _encode_labels(self):
[Optional] If you want to spend time doing something for literally no benefit, it could be nice to make base classes for `Dataset`s and `MultiLabelDataset`s that implement common methods like this so we only need to change a single place in the future. I understand if you don't want to do that, but whenever I see an opportunity for inheritance, I lose all control.

2021-02-04 18:54 UTC, nathancooperjones commented on tests/fixtures/learner_fixtures.py
> +                           'category': [1, 2]})
We seem to use this in multiple fixtures, so it might be nice to just make this its own fixture that other fixtures can use, I.e.: 

```python
@pytest.fixture()
def df_string():
      return pd.DataFrame({'image_loc': ['sample_data/tonks.jpeg', 'sample_data/tonks.jpeg'],
                           'fake_text': ['sample_data/tonks.jpeg', 'sample_data/tonks.jpeg'],
                           'category': ['cat', 'dog']})

... 

@pytest.fixture()
def mixed_labels(df_string, df_int):
    ... 
```

2021-02-04 18:54 UTC, nathancooperjones commented on tests/fixtures/learner_fixtures.py
> +                           'category': [[1, 2], [2]]})
Same here!

2021-02-04 18:54 UTC, nathancooperjones commented on tests/fixtures/learner_fixtures.py
> +    return dataset_loader, dataset_loader2
What do you think about pulling this out as a helper function that lives in `learner_fixtures.py` that every fixture can call with the task datasets to get back the data loader?

2021-02-04 18:54 UTC, nathancooperjones commented on tests/fixtures/learner_fixtures.py
> +        crop_transform='train'
Does it matter that these are also `train` and not `val`?

2021-02-04 18:54 UTC, nathancooperjones commented on tests/test_learner.py
> +    assert ('Mapping mismatch in task1 task. Check that all categories' in str(e.value)) is True
Nice test!

2021-02-04 18:56 UTC, nathancooperjones commented
Also @sugi-chan can we make a ticket to update tutorial notebooks to use this new label encoder strategy?

2021-02-04 19:43 UTC, sugi-chan commented on octopod/ensemble/dataset.py
> +        le = preprocessing.LabelEncoder()
yeah I thought that eas an interesting output... so yeah when we have numeric inputs we have really boring mappings lol

2021-02-05 16:30 UTC, sugi-chan commented on octopod/ensemble/dataset.py
> +        label = self.label_encoder.transform([label])[0]
yeah we could technically use the encoder. it is slightly more annoying w/ the multi-label one, but I can also adjust those

2021-02-05 16:32 UTC, sugi-chan commented on octopod/ensemble/dataset.py
> +        a list of binary encoded categories or strings with length equal to number of
technically lists... I guess it also works with pandas columns.... so it might just be iterables we can index into.

2021-02-05 16:34 UTC, sugi-chan commented on octopod/ensemble/dataset.py
> +        which will be encoded using a sklearn label encoder
yeah thats probably a typo from some pt in the past

2021-02-05 16:35 UTC, sugi-chan commented on octopod/learner.py
> +                raise Exception(f'Mapping mismatch in {task} task. Check that all categories are '
fair

2021-02-05 21:38 UTC, sugi-chan commented on octopod/ensemble/dataset.py
> +        which will be encoded using a sklearn label encoder
yeah looking at im guessing i swapped the y descriptions between the multi-label and regular datasets at some pt

2021-02-05 21:43 UTC, sugi-chan commented on octopod/text/dataset.py
> +    def _encode_labels(self):
decent future ticket... but im also less motivated by refactoring LOL

2021-02-05 22:02 UTC, sugi-chan commented on tests/fixtures/learner_fixtures.py
> +        crop_transform='train'
not really but can swap out

2021-02-08 16:57 UTC, sugi-chan commented on octopod/ensemble/dataset.py
> +        label = self.label_encoder.transform([label])[0]
So I think for now we should leave it as using the tranforms from the sklearn encoders. For the multi-class ones it doesnt really matter. the multi-label biz I would probably just copy over the inverse_transform code into octopod 

https://github.com/scikit-learn/scikit-learn/blob/95119c13a/sklearn/preprocessing/_label.py#L660

2021-02-08 22:17 UTC, nathancooperjones commented on octopod/learner.py
> +        all the same labels present maps. If they do not then an error will be thrown.
```suggestion
        all the same labels present maps. If they do not then a ValueError will be thrown.
```

2021-02-08 22:17 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        a list of binary encoded categories or strings with length equal to number of
Should this be a `list of lists` too to match the input for the text and vision datasets?

2021-02-08 22:17 UTC, nathancooperjones commented on octopod/text/dataset.py
> +        using a sklearn label encoder to [1,0,0,1].
Nice example!!

2021-02-08 22:17 UTC, nathancooperjones commented on tests/fixtures/learner_fixtures.py
> +    return gen_train_val_dataloaders_helper(task1_dataset, task2_dataset)
Nice!!!!!

2021-02-08 22:18 UTC, nathancooperjones commented on octopod/ensemble/dataset.py
> +        label = self.label_encoder.transform([label])[0]
Makes sense to me!

2021-02-08 22:20 UTC, nathancooperjones commented on octopod/learner.py
> +    NOTES
[Optional] I think it's also okay to put this explanation in the docstring under `val_dataloader ` above this unless you like it better in `NOTES`.

2021-02-08 22:21 UTC, sugi-chan commented on octopod/learner.py
> +        all the same labels present maps. If they do not then an error will be thrown.
ugh forgetting to update notes

2021-02-08 22:35 UTC, sugi-chan commented on octopod/learner.py
> +    NOTES
I just dumped notes into both the train and val dataloader notes LOL

2021-02-08 22:54 UTC, nathancooperjones approved these changes
Woo-hoo!!!! LGTM! 🎉  

![](https://media0.giphy.com/media/j4q4h9uWKWwnYT1k3Z/giphy.gif)

2021-02-10 15:10 UTC, merged