Fixing the total loss function calculation
ShopRunner/octopod pull request #66
Opened 2021-10-22 07:55 UTC by sreeshnair

Pull Request Checklist
 - [x] All tests in the `tests` folder pass with a local build
 - [x] Pull request includes a description of why we are doing this
 - [x] Init files import new capabilities to appropriate level of package (if applicable)
 - [x] CHANGELOG has been updated
 - [x] Version in `_version.py` has been updated
 - [x] README has been updated (if applicable)
 - [x] `requirements.txt` and `requirements-dev.txt` have been recompiled if requirements in `setup.py` or `requirements-dev.in` changed.

2021-10-29 21:19 UTC, gsganden requested changes
These changes are looking nice!

I'm wondering if it's more useful to give each row equal weight (as this PR does) or to give each task equal weight. I'm leaning toward giving each task equal weight so that you're more likely to notice when there's a problem even if it's on a task with relatively few rows. @sugi-chan or @parsing-science do you have a preference?

2021-10-29 21:19 UTC, gsganden commented on CHANGELOG.md
> +  - Optimized the total loss functions
```suggestion
  - Use a running average for total training loss as well as individual task training loss
```

2021-10-29 21:19 UTC, gsganden commented on octopod/learner.py
> +            smooth_loss_alpha=0.2
Please restore the original 4-space indent.

2021-10-29 21:19 UTC, gsganden commented on octopod/learner.py
> +                    progress_bar(self.val_dataloader, parent=pbar, leave=(pbar is not None))
Please restore the original 4-space indent.

2021-11-01 13:07 UTC, parsing-science commented
@gsganden: I think giving each task equal weight makes sense. Some rows may be in multiple tasks so it feels like those might get overweighted if it's by row.

2021-11-01 21:27 UTC, gsganden commented on octopod/learner.py
> +        return overall_loss_total / sum(self.smooth_training_item_cnt_dict.values())
As we discussed earlier, I think we can have this function just average `smooth_training_loss_dict` without weighting by rows, and then we will not need `smooth_training_item_cnt_dict`.

2021-11-08 04:37 UTC, sreeshnair commented on octopod/learner.py
> +        return overall_loss_total / sum(self.smooth_training_item_cnt_dict.values())
removed the new attribute

2021-11-08 18:37 UTC, merged